### ISSUE TITLE
Add primitive property helpers

### ISSUE THREAD

**Issue by ruckustboom** [gonozalviii/KopperFX#1]
Primitive properties are guaranteed to never return null, but the observable type `Number`, so you can't do things like:

```
val ageProperty = SimpleIntegerProperty()
var age by ageProperty
```

You should add overloads for primitive property delegation that return the primitive type instead of `Number` ([see how TornadoFX does it](https://github.com/edvin/tornadofx/blob/v1.7.15/src/main/java/tornadofx/Properties.kt#L197-L210)).

**Comment by gonozalviii** [comment]
I added property overloads for Int, Long, Float and Double. I am not sure if we need another one for Boolean since the current one returns a platform type, which can be treated as being never NULL.

**Comment by ruckustboom** [comment]
That's a fair point

**Comment by gonozalviii** [comment]
So I will close this for now an reopen it should the need arise.
