### ISSUE TITLE
Add range overloads to the removeRange functions

### ISSUE THREAD

**Issue by ruckustboom** [gonozalviii/KopperFX#2]
Several of your extensions add a `removeRange(from: Int, to: Int)` function. You might as well add a `removeRange(range: IntRange)` extension as well.

**Comment by rvictor89** [comment]
Great idea! We will add this as soon as possible :)

**Comment by rvictor89** [comment]
Added with commit 083bafa731ebc259085430f9bfb60791d60ee0c3 you can now use following code for example:

`pane.removeRange(0..2)`

This will be added with Release 0.5
