### ISSUE TITLE
Add launch function

### ISSUE THREAD

**Issue by ruckustboom** [gonozalviii/KopperFX#3]
I find a super useful function is

```
inline fun <reified T : Application> launch(vararg args: String) = Application.launch(T::class.java, *args)
```

when then lets you write

```
fun main(args: Array<String>) = launch<MyApp>(*args)
```

**Comment by gonozalviii** [comment]
Thank you for the suggestion!

I added 2 versions for the launch method:
```
inline fun <reified T: Application> launch(args: Array<String>)
inline fun <reified T: Application> launch(args: Array<String>, preloader: KClass<out Preloader>)
```
which lets you do:
`fun main(args: Array<String>) = launch<MyApp>(args)`

or with pre-loader:
`fun main(args: Array<String>) = launch<MyApp>(args, MyPreloader::class)`

**Comment by ruckustboom** [comment]
Nice
