### ISSUE TITLE
Add simplified FxmlApp class

### ISSUE THREAD

**Issue by ruckustboom** [gonozalviii/KopperFX#4]
I find the boilerplate for launching an app can be annoying. I have this class that I tend to use a lot:

```
abstract class FxmlApp(private val fxml: String, private val title: String = "Demo") : Application() {
    override fun start(primaryStage: Stage) {
        val root: Parent = FXMLLoader.load(javaClass.getResource(fxml))
        primaryStage.title = this.title
        val scene = Scene(root)
        primaryStage.scene = scene
        beforeShow(primaryStage, scene, root)
        primaryStage.show()
    }

    open fun beforeShow(stage: Stage, scene: Scene, root: Parent) = Unit
}
```
which I then use like so
```
fun main(args: Array<String>) = launch<DemoApp>(*args)
class DemoApp: FxmlApp("/demo-app.fxml")
```

**Comment by gonozalviii** [comment]
I very much like the idea. I'd also like to support building more complex GUIs by combining multiple FXML-files and maybe using a dependency injection framework. I'm not sure if I can fit that into one configurable class. Creating multiple helper classes might be a better solution. I will experiment a little on that.

**Comment by gonozalviii** [comment]
I ended up adding the template exactly as you suggested. Supporting more complex GUIs would effectively save 2 lines (set title, show stage) while adding a lot of complexity to the template class.
